### ISSUE TITLE
Implement Weibull distribution

### ISSUE THREAD

**Issue by TUBSAiPTL** [IndEcol/ODYM#18]
Hi there,

I want to use a Weibull distribution, but I am not sure how to script it. These are my parameters:

α = shape, β = scale
α = 6.32499, β = 14.3862

I tried to do it like this, but obviously did not work: 
<img width="998" alt="image" src="https://user-images.githubusercontent.com/98967109/160108317-73dde8a0-a85f-4a7e-a1b6-79413197bb19.png">

From Tutorial 6 I saw that Scale and Shape are supposed to be arrays. But what do they need to include? I tried to figure it out with the stats_arrays documentation online but could not find examples for Weibull that helped me.

Thanks again and kind regards !

**Comment by CBreton026** [comment]
Hi @TUBSAiPTL, 

I haven't looked at all your code, but the first thing that comes to mind is that your parameters should use a decimal point rather than a comma.

For example, alpha = 6,32499 will return a tuple, rather than the actual float value that you need.

Can you see if this fixes your problem?

**Comment by TUBSAiPTL** [comment]
Hi @CBreton026,

thanks for your reply. I had the same in mind already, but it still gave me this error:

![image](https://user-images.githubusercontent.com/98967109/160138185-81f17b93-050f-4159-9460-a61eac79968e.png)

**Comment by nheeren** [comment]
I should be able to help you / send some code. 

> From Tutorial 6 I saw that Scale and Shape are supposed to be arrays. But what do they need to include? I tried to figure it out with the stats_arrays documentation online but could not find examples for Weibull that helped me.

Can you quote the code here or refer to it in this repo, please?

**Comment by TUBSAiPTL** [comment]
Sorry for the late reply. Your help would be great !

This is the code in the Tutorial:
<img width="871" alt="image" src="https://user-images.githubusercontent.com/98967109/160769063-f6c1541b-d8ed-4d27-8f5e-0b66d0530df2.png">

The referred data looks like this:
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/98967109/160769396-f6a39f9c-d6d3-4374-bec0-1ebef2461ba0.png">

I assume that I need to define the stats_array string correctly, but I cannot figure out the correct structure.

My goal is to have a lifetime that is determined by a Weibull distribution, meaning that I have a given ave, min, max, alpha, beta for each battery in the model.

**Comment by stefanpauliuk** [comment]
Hi @TUBSAiPTL , the lifetime model is flexible regarding whether a single lifetime or a yearly lifetime is given.
But in any case, the lifetime must be supplied as list, so for a fixed lifetime, it is [alpha] and [beta] instead of alpha and beta. You see that the shape and scale parameters are put into square brackets [].

**Comment by TUBSAiPTL** [comment]
Hi @stefanpauliuk & @nheeren,

thank you both for helping out and giving advise. Having a look at the data file above and knowing that it is supposed to be a list, I managed to implement a Weibull distribution as well as lognormal or normal distribution.

Cheers.
